/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    RedPacket: {
      address: "0xA9eFbD651C1a20941c8F6FFEBCeE1eC9AC75782F",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "packetId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "claimer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PacketClaimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "packetId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalPackets",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPasswordProtected",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          name: "PacketCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "packetId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PacketRefunded",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "packetId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "password",
              type: "string",
            },
          ],
          name: "claimPacket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "totalPackets",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "password",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "durationInHours",
              type: "uint256",
            },
          ],
          name: "createPacket",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "packetId",
              type: "uint256",
            },
          ],
          name: "getPacketInfo",
          outputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "remainingAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPackets",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "claimedPackets",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPasswordProtected",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isActive",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "packetId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "claimer",
              type: "address",
            },
          ],
          name: "hasClaimed",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextPacketId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "packets",
          outputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "remainingAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPackets",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "claimedPackets",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "password",
              type: "string",
            },
            {
              internalType: "bool",
              name: "isPasswordProtected",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isActive",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "packetId",
              type: "uint256",
            },
          ],
          name: "refundPacket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9409320,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
